### ISSUE TITLE
Make --index-url a global option.

### ISSUE THREAD

**Issue by rlbaker** [osupython/pip2#20]
--index-url is going to be used across multiple commands and should probably be a global option rather than a sub-parser option. We should also look at what other options are global as well.

**Comment by rlbaker** [comment]
After testing this today, global options become positional if subparsers are present.
Ex:

```
pip2 install test_package -i http://simple.crate.io    # Does not work
pip2 -i http://simple.crate.io install test_package    # Works as expected
```

I feel like global options should be able to be passed in anywhere so maybe we should investigate this a little more.

**Comment by njwilson** [comment]
Does putting the global options in a "parent" parser like this help?

http://stackoverflow.com/questions/7498595/python-argparse-add-argument-to-multiple-subparsers

**Comment by rlbaker** [comment]
Looks like that is exactly what we need to do. Thanks!
