### ISSUE TITLE
Search - packaging logger warning

### ISSUE THREAD

**Issue by michaeta** [osupython/pip2#43]
When an IrrationalVersionError is raised by Client.search_projects() within packaging\pypi\xmlrpc.py, the function logs the exception to the packaging logger as a warning. This produces output to the command line, the exception contains the version number that cannot be rationalized, but not the package name. All logs are done in the API call before the CLI_wrapper prints output so we cannot tell which package is creating the error unless some extra code is added. Currently the packaging logger's level is switched to record only errors while search_projects() is executed and then changed back to what it was previously. Is this how we want to handle this or are there other suggestions?

**Comment by merwok** [comment]
Do you have a list of commands or a code snippet that I can use to reproduce the bug?  Please also tell what Python version was used.

**Comment by michaeta** [comment]
I used Python 3.3 alpha 2 release. Here is an example to reproduce the issue.

Example:

```
(ENV33) C:\Users\PPDT\Documents\CS46X\PPDT>python
Python 3.3.0a2 (default, Apr  1 2012, 19:34:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import packaging.pypi.xmlrpc
>>> c = packaging.pypi.xmlrpc.Client()
>>> a = c.search_projects("py")
Irrational version error found: 02 Jun 2010
Irrational version error found: 0.26unleak
Irrational version error found: 2012.1.2
Irrational version error found: 2011.1
Irrational version error found: 1.0.22-unbroken
>>>
```

**Comment by njwilson** [comment]
@michaeta, I suggest removing the code in `commands/search.py` that temporarily changes the logging level in distutils2/packaging to hide these warnings/errors.

The output of our search command will look something like this (a bunch of irrational version errors followed by the actual search results), but that's fine for now:

```
$ pip2 search req
Irrational version error found: 20120106
Irrational version error found: k303-q100 code name: virtual
Irrational version error found: 0.0.0-prealpha
Irrational version error found: 20071211
Irrational version error found: devel
Irrational version error found: 0.1dev-20110502
django-simple-autocomplete - App enabling the use of jQuery UI autocomplete widget for ModelChoiceFields with minimal configuration required.
five.globalrequest         - Zope 2 integration for zope.globalrequest
...
```

Though I do agree that distutils2/packaging should be modified to include the name of the package that has a bad version.

**Comment by merwok** [comment]
Okay, so this is actually three bugs.  The first is that the IrrationalVersion exception should include the project name; this is not reported yet on bugs.python.org.  The second is already known: warnings about invalid versions are useful when creating a project or registering metadata on PyPI, but they’re useless when you do a list or search operation and the warnings from other people’s projects are not relevant to you.  Last, and this one is known too, these warnings should happen only for projects using metadata v1.2 (PEP 345), not older (current) versions (1.0 and 1.1, PEP 241 and 314, what distutils and setuptools produce).

**Comment by njwilson** [comment]
Alright, the first bug (the only previously unknown/unreported one) has now been reported at http://bugs.python.org/issue14778

@michaeta, we should be able to close this issue and not worry about the upstream bugs once the logging level hack is removed from the search command.
