### ISSUE TITLE
Search results differ between pip and pip2

### ISSUE THREAD

**Issue by njwilson** [osupython/pip2#58]
pip2 only returns a subset of the search results returned by the original pip. I'm guessing pip2 is only searching over package names while the original pip searches over package names **and** descriptions (and maybe more fields).

We should check which fields pip searches and do the same in pip2.

Original pip:

```
$ pip search cheese
EggBasket                 - A simple, lightweight Python Package Index (aka Cheeseshop) clone.
an_example_pypi_project   - An demonstration of how to create, document, and publish to the cheese shop a5 pypi.org.
g-pypi                    - Tool for creating Gentoo ebuilds for Python packages by querying PyPI (The Cheese Shop)
cheese-freezer            - Upload helper for your local PyPI mirror
sphinxcontrib-cheeseshop  - Sphinx extension cheeseshop
Cheesecake                - Computes "goodness" index for Python packages based on various empirical "kwalitee" factors
CheesePrism               - CheesePrism
check_qbeanstalk          - A simple program to monitor the current jobs on queue to the cheese shop a5 pypi.org.
HelloGUI                  - An demonstration of how to create, document, and publish to the cheese shop a5 pypi.org.
PyGouda                   - The EasyCheese of GPU programming
```

pip2:

```
$ pip2 search cheese
Cheesecake                 - Computes "goodness" index for Python packages based on various empirical "kwalitee" factors
sphinxcontrib-cheeseshop   - Sphinx extension cheeseshop
CheesePrism                - CheesePrism
cheese-freezer             - Upload helper for your local PyPI mirror
```

**Comment by michaeta** [comment]
Pip2 searches package names and their summary, but that's it. I'm not sure what fields pip searches on though I know it's at least name and summary as well.

**Comment by njwilson** [comment]
Oops, I was using an old version in the `pip2` script because I hadn't gone a `python setup.py install/develop` in a while. It looks like you modified it to search the description field on May 1st. pip and pip2 now show the same results for the 'cheese' search. They are sorted a bit differently though. Odd.
